# 01_extract_ukb_tabular_data.R
#
# Minimal UK Biobank tabular-data extraction script for the Dynamic SFC study.
#
# Purpose
# -------
# This script documents the UK Biobank tabular fields required by the analyses
# and extracts them from a legacy downloaded UKB bulk table. The original study
# was performed before migration to the UK Biobank Research Analysis Platform
# (RAP), so this script reproduces the legacy tabular extraction step rather
# than providing a RAP-native workflow.
#
# Important
# ---------
# 1. No participant-level UKB data are distributed with this repository.
# 2. Users must have their own authorized UK Biobank data access.
# 3. Column naming differs across historical UKB export/conversion tools.
#    The helper below recognizes several common formats and preserves the
#    original source column names in the extracted files.
# 4. Imaging-derived variables (e.g., SFC/DSFC, TIV, MRI scaling, head motion,
#    SNR) and genetic-derived variables (PRS/APOE genotype) are generated by
#    separate pipelines and are therefore not reconstructed here.

library(data.table)

# -------------------------------------------------------------------------
# User configuration
# -------------------------------------------------------------------------

bulk_file <- Sys.getenv("UKB_BULK_FILE", unset = "PATH/TO/UKB_BULK_TABLE.csv")
output_dir <- Sys.getenv("UKB_EXTRACT_DIR", unset = "derived/tabular")

if (!file.exists(bulk_file)) {
  stop(
    "UKB bulk table not found. Set environment variable UKB_BULK_FILE ",
    "to the authorized local UK Biobank tabular export."
  )
}

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

# -------------------------------------------------------------------------
# Field definitions
# -------------------------------------------------------------------------
# These IDs are intentionally explicit so that the provenance of every
# participant-level variable used downstream can be inspected without
# requiring the original laboratory-wide preprocessing script.

# Demographic / general covariates used in the original preprocessing.
basic_fields <- c(
  31,     # Sex
  34,     # Year of birth
  52,     # Month of birth
  54,     # UK Biobank assessment centre
  53,     # Date of attending assessment centre
  21022,  # Age at recruitment
  21003,  # Age when attended assessment centre
  21001,  # Body mass index (BMI)
  21000,  # Ethnic background
  20022,  # Birth weight
  1707,   # Handedness
  22189,  # Townsend deprivation index
  845     # Education-related field used in original preprocessing
)

# Cognitive / behavioral outcomes explicitly referenced by the manuscript
# analysis code.
outcome_fields <- c(
  135,
  137,
  1970,
  2010,
  2178,
  2188,
  4282,   # Maximum digits remembered correctly
  4526,
  4548,
  6373,   # Matrix pattern completion
  20016,  # Fluid intelligence score
  20197   # Paired-associate learning / cognition-related field
)

# Lifestyle variables used in the original preprocessing script.
# Keeping the complete study-specific lifestyle field set makes the extraction
# transparent even when only a subset is used in a particular figure/model.
lifestyle_fields <- c(
  20117, 1558, 1568, 1578, 1588, 1598, 1608, 4407, 4418, 4429, 4440, 4451,
  1309, 1319, 1289, 1299, 1329, 1339, 1349, 1369, 1379, 1389, 1438, 1448,
  1458, 1468, 884, 894, 904, 914, 1160, 20116, 1070, 1080, 709, 1031, 6160,
  738, 20022, 20495, 20497, 22189
)

# Genetic covariates used by downstream PRS/APOE models.
genetic_covariate_fields <- c(
  22000,  # Genotyping measurement batch
  22001,  # Genetic sex
  22006,  # Genetic ethnic grouping
  22009   # Genetic principal components (array field)
)

# rfMRI quality / acquisition covariates used in the preprocessing.
rfmri_covariate_fields <- c(
  25923,  # Echo time for rfMRI
  25929,  # Intensity scaling for rfMRI
  24438,  # Mean absolute head motion from rfMRI
  25741,  # Mean rfMRI head motion
  25744,  # Inverted temporal SNR in artefact-cleaned rfMRI
  25743   # Inverted temporal SNR in preprocessed rfMRI
)

field_groups <- list(
  basic = sort(unique(basic_fields)),
  outcomes = sort(unique(outcome_fields)),
  lifestyle = sort(unique(lifestyle_fields)),
  genetic_covariates = sort(unique(genetic_covariate_fields)),
  rfmri_covariates = sort(unique(rfmri_covariate_fields))
)

all_required_fields <- sort(unique(unlist(field_groups)))

# -------------------------------------------------------------------------
# Helpers
# -------------------------------------------------------------------------

# Return TRUE for a column belonging to a UKB field ID.
# Supported examples include:
#   21003-2.0
#   21003.2.0
#   f.21003.2.0
#   x21003_2_0
column_matches_field <- function(column_name, field_id) {
  patterns <- c(
    paste0("^", field_id, "[-\\.]"),
    paste0("^f\\.", field_id, "\\."),
    paste0("^x", field_id, "_"),
    paste0("^", field_id, "$")
  )
  any(vapply(patterns, grepl, logical(1), x = column_name))
}

select_columns_for_fields <- function(column_names, field_ids) {
  keep <- column_names %in% c("eid", "FID", "IID")
  for (field_id in field_ids) {
    keep <- keep | vapply(
      column_names,
      column_matches_field,
      logical(1),
      field_id = field_id
    )
  }
  column_names[keep]
}

extract_group <- function(dt, field_ids, output_name) {
  selected <- select_columns_for_fields(names(dt), field_ids)

  if (!("eid" %in% selected)) {
    stop(
      "No 'eid' column was detected. Please rename the participant identifier ",
      "column to 'eid' before running this script."
    )
  }

  out <- dt[, ..selected]
  fwrite(out, file.path(output_dir, output_name), na = "NA")
  invisible(out)
}

# -------------------------------------------------------------------------
# Read bulk table and extract study-specific subsets
# -------------------------------------------------------------------------

message("Reading UKB bulk table: ", bulk_file)
ukb <- fread(bulk_file, showProgress = TRUE)

message("Extracting demographic/general covariates...")
extract_group(
  ukb,
  field_groups$basic,
  "UKB_basic_fields.csv"
)

message("Extracting cognitive/health outcome fields used by the analysis code...")
extract_group(
  ukb,
  field_groups$outcomes,
  "UKB_outcome_fields.csv"
)

message("Extracting lifestyle fields...")
extract_group(
  ukb,
  field_groups$lifestyle,
  "UKB_lifestyle_fields.csv"
)

message("Extracting genetic covariate fields...")
extract_group(
  ukb,
  field_groups$genetic_covariates,
  "UKB_genetic_covariate_fields.csv"
)

message("Extracting rfMRI acquisition/quality covariates...")
extract_group(
  ukb,
  field_groups$rfmri_covariates,
  "UKB_rfmri_covariate_fields.csv"
)

# -------------------------------------------------------------------------
# Field manifest
# -------------------------------------------------------------------------
# A machine-readable manifest is written for provenance and repository review.

field_manifest <- rbindlist(
  lapply(names(field_groups), function(group_name) {
    data.table(
      group = group_name,
      field_id = field_groups[[group_name]]
    )
  })
)

fwrite(
  field_manifest,
  file.path(output_dir, "UKB_field_manifest.csv")
)

# Report fields that were requested but not found in this particular export.
available_columns <- names(ukb)
missing_fields <- all_required_fields[
  !vapply(
    all_required_fields,
    function(id) any(vapply(
      available_columns,
      column_matches_field,
      logical(1),
      field_id = id
    )),
    logical(1)
  )
]

if (length(missing_fields) > 0) {
  warning(
    "The following requested UKB field IDs were not detected in the supplied ",
    "bulk table: ",
    paste(missing_fields, collapse = ", "),
    ". This may reflect a different UKB export/application or column naming scheme."
  )
}

message("Extraction complete. Files written to: ", normalizePath(output_dir))
