%% 02_compute_sfc_dsfc_glasser.m
%
% Compute static and dynamic structure-function coupling (SFC/DSFC)
% for UK Biobank participants.
%
% INPUT DATA
% ----------
%
% Resting-state fMRI:
%
%   fMRI_Glasser_TS_2_0
%       N x 1 cell array.
%       Each cell contains the participant-level regional BOLD time series.
%
%   fMRI_Glasser_eID_2_0
%       N x 1 participant-ID vector.
%
%
% Structural connectivity:
%
%   connectome_streamline_count_10M_2_0
%       M x 1 cell array.
%       Each cell contains a participant-level structural connectivity matrix.
%
%   dMRI_Glasser_S1_eID_2_0
%       M x 1 participant-ID vector.
%
%
% The imaging inputs were obtained from UKB Connectome data releases and
% reorganized from the corresponding UKB bulk files into MATLAB-compatible
% participant-level cell arrays before analysis.
%
% Participant-level UK Biobank data are not distributed with this repository.
%
%
% OUTPUT
% ------
%
% common_eid
% SCDFCC_Mean
% SCDFCC_SD
% SCDFCC_Diff
% SCDFCC_All
%
%
% Original analyses were performed using MATLAB R2018b on a Linux HPC cluster.
% ==========================================================================

clearvars -except WINDOW_LENGTH WINDOW_STEP N_WORKERS

tic

%% ------------------------------------------------------------------------
% Load configuration
% -------------------------------------------------------------------------

if ~exist('config.m', 'file')
    error( ...
        ['config.m was not found. ', ...
         'Copy config_example.m to config.m and configure the paths.'] ...
    );
end

run('config.m');

fprintf('Configuration loaded.\n');

fprintf( ...
    'Window length = %d TR\n', ...
    WINDOW_LENGTH ...
);

fprintf( ...
    'Window step   = %d TR\n', ...
    WINDOW_STEP ...
);

fprintf( ...
    'Workers       = %d\n', ...
    N_WORKERS ...
);

%% ------------------------------------------------------------------------
% Load imaging data
% -------------------------------------------------------------------------

fprintf('\nLoading resting-state fMRI data...\n');

load( ...
    FMRI_FILE, ...
    'fMRI_Glasser_TS_2_0', ...
    'fMRI_Glasser_eID_2_0' ...
);

fprintf('Loading structural connectivity data...\n');

load( ...
    SC_FILE, ...
    'connectome_streamline_count_10M_2_0', ...
    'dMRI_Glasser_S1_eID_2_0' ...
);

fprintf('Imaging data loaded.\n');

%% ------------------------------------------------------------------------
% Match participants across modalities
% -------------------------------------------------------------------------

common_eid = intersect( ...
    fMRI_Glasser_eID_2_0, ...
    dMRI_Glasser_S1_eID_2_0, ...
    'stable' ...
);

fprintf( ...
    'Participants with both fMRI and dMRI: %d\n', ...
    length(common_eid) ...
);

fmri_idx = ismember( ...
    fMRI_Glasser_eID_2_0, ...
    common_eid ...
);

dmri_idx = ismember( ...
    dMRI_Glasser_S1_eID_2_0, ...
    common_eid ...
);

fMRI_Glasser_TS_2_0 = ...
    fMRI_Glasser_TS_2_0(fmri_idx);

fMRI_Glasser_eID_2_0 = ...
    fMRI_Glasser_eID_2_0(fmri_idx);

connectome_streamline_count_10M_2_0 = ...
    connectome_streamline_count_10M_2_0(dmri_idx);

dMRI_Glasser_S1_eID_2_0 = ...
    dMRI_Glasser_S1_eID_2_0(dmri_idx);

%% ------------------------------------------------------------------------
% Ensure identical participant order
% -------------------------------------------------------------------------

[~, fmri_order] = ismember( ...
    common_eid, ...
    fMRI_Glasser_eID_2_0 ...
);

[~, dmri_order] = ismember( ...
    common_eid, ...
    dMRI_Glasser_S1_eID_2_0 ...
);

fMRI_Glasser_TS_2_0 = ...
    fMRI_Glasser_TS_2_0(fmri_order);

connectome_streamline_count_10M_2_0 = ...
    connectome_streamline_count_10M_2_0(dmri_order);

%% ------------------------------------------------------------------------
% Calculate parcel sizes
% -------------------------------------------------------------------------

fprintf('\nCalculating Glasser parcel sizes...\n');

roi_tmp = parcel_to_surface( ...
    1:N_CORTICAL_PARCELS, ...
    ATLAS_NAME ...
);

roi_size = zeros( ...
    N_CORTICAL_PARCELS, ...
    1 ...
);

for roi = 1:N_CORTICAL_PARCELS

    roi_size(roi) = sum( ...
        roi_tmp == roi ...
    );

end

%% ------------------------------------------------------------------------
% Start MATLAB parallel pool
% -------------------------------------------------------------------------

poolobj = gcp('nocreate');

if isempty(poolobj)

    fprintf( ...
        '\nStarting MATLAB parallel pool with %d workers...\n', ...
        N_WORKERS ...
    );

    parpool( ...
        'local', ...
        N_WORKERS ...
    );

end

%% ------------------------------------------------------------------------
% Preallocate outputs
% -------------------------------------------------------------------------

N = length(common_eid);

SCDFCC_Mean = nan( ...
    N, ...
    N_CORTICAL_PARCELS ...
);

SCDFCC_SD = nan( ...
    N, ...
    N_CORTICAL_PARCELS ...
);

SCDFCC_Diff = nan( ...
    N, ...
    N_CORTICAL_PARCELS ...
);

SCDFCC_All = cell( ...
    N, ...
    1 ...
);

%% ------------------------------------------------------------------------
% Dynamic structure-function coupling
% -------------------------------------------------------------------------

fprintf('\nStarting dynamic SFC calculation...\n');

analysis_start = tic;

parfor i = 1:N

    %% Structural connectivity

    xSC = connectome_streamline_count_10M_2_0{i};

    xSC = xSC( ...
        1:N_CORTICAL_PARCELS, ...
        1:N_CORTICAL_PARCELS ...
    );

    % Normalize streamline counts by parcel-pair surface size.

    parcel_pair_size = ...
        repmat(roi_size, 1, N_CORTICAL_PARCELS) .* ...
        repmat(roi_size, 1, N_CORTICAL_PARCELS)';

    xSC = xSC ./ parcel_pair_size;

    xSCvec = icatb_mat2vec(xSC);

    %% Functional time series

    TS = fMRI_Glasser_TS_2_0{i}';

    %% Dynamic functional connectivity

    [xDFC, xDFCvec] = DynFunConn( ...
        TS, ...
        WINDOW_LENGTH, ...
        WINDOW_STEP ...
    );

    %% Dynamic structure-function coupling

    SCDFCC = SDFC( ...
        xSC, ...
        xDFC ...
    );

    %% Summary measures

    SCDFCC_Mean(i, :) = mean( ...
        SCDFCC, ...
        1, ...
        'omitnan' ...
    );

    SCDFCC_SD(i, :) = std( ...
        SCDFCC, ...
        0, ...
        1, ...
        'omitnan' ...
    );

    SCDFCC_Diff(i, :) = mean( ...
        abs(diff(SCDFCC, 1, 1)), ...
        1, ...
        'omitnan' ...
    );

    %% Whole-window edge-wise SC-FC correlation

    SCDFCC_All{i, 1} = corr( ...
        xSCvec, ...
        xDFCvec', ...
        'type', ...
        'Spearman', ...
        'rows', ...
        'pairwise' ...
    );

end

costtime = toc(analysis_start);

fprintf( ...
    '\nDynamic SFC calculation completed in %.2f seconds.\n', ...
    costtime ...
);

%% ------------------------------------------------------------------------
% Save results
% -------------------------------------------------------------------------

output_file = fullfile( ...
    OUTPUT_DIR, ...
    sprintf( ...
        'ukb_glasser_sfc_dsfc_streamline_count_%dTR.mat', ...
        WINDOW_LENGTH ...
    ) ...
);

save( ...
    output_file, ...
    'common_eid', ...
    'SCDFCC_Mean', ...
    'SCDFCC_SD', ...
    'SCDFCC_Diff', ...
    'SCDFCC_All', ...
    'WINDOW_LENGTH', ...
    'WINDOW_STEP', ...
    '-v7.3' ...
);

fprintf('\nResults saved to:\n%s\n', output_file);

fprintf('\nTotal script time: %.2f seconds.\n', toc);
