function results = run_demographic_age_associations(window_length)
% RUN_DEMOGRAPHIC_AGE_ASSOCIATIONS
%
% Reproduce the demographic and age-related mixed-effects analyses from the
% original MATLAB master script.
%
% Requires analysis-ready participant tables with a common 'eid' identifier.
%
% Required input tables:
%   UKB_Basic.csv
%   UKB_BrainMRICov.csv
%   brain_data_<window>TR.mat
%
% Required custom functions:
%   LMM_with_EffectSizes_Full
%   LMM_withFormula_Interact
%
% Original analysis conventions are preserved wherever possible.
%
% -------------------------------------------------------------------------

if nargin < 1 || isempty(window_length)
    window_length = 30;
end

run('00_config.m');

table_dir = fullfile(OUTPUT_DIR, 'analysis_tables');

brain_file = fullfile( ...
    table_dir, ...
    sprintf('brain_data_%dTR.mat', window_length));

if ~exist(brain_file, 'file')
    error('Run prepare_sfc_analysis_tables.m first.');
end

load(brain_file, 'brain_data_7n', 'brain_data_360p');

basic_file = fullfile(DATA_ROOT, 'tabular', 'UKB_Basic.csv');
mri_cov_file = fullfile(DATA_ROOT, 'tabular', 'UKB_BrainMRICov.csv');

UKB_Basic = readtable(basic_file);
UKB_BrainMRICov = readtable(mri_cov_file);

outcomes_file = fullfile(DATA_ROOT, 'tabular', 'UKB_Outcomes_2_0.csv');
if exist(outcomes_file, 'file')
    UKB_Outcomes_2_0 = readtable(outcomes_file);
else
    UKB_Outcomes_2_0 = table();
end

results = struct();

% -------------------------------------------------------------------------
% Yeo-7 analyses
% -------------------------------------------------------------------------

UKB_BrainXY = innerjoin( ...
    innerjoin(UKB_Basic, UKB_BrainMRICov, 'Keys', 'eid'), ...
    brain_data_7n, ...
    'Keys', 'eid');

if ismember('HeadMotion_2_0', UKB_BrainXY.Properties.VariableNames)
    UKB_BrainXY(UKB_BrainXY.HeadMotion_2_0 > 0.2, :) = [];
end

YList = brain_data_7n.Properties.VariableNames(2:end)';

% Age
formula = [ ...
    'AgeAttend_2_0^2+Sex_0_0+BMI_2_0+HeadMotion_2_0+', ...
    'Race_1+Race_2+Race_3+Race_4+Vol_WB_TIV_2_0+(1|Centre_0_0)' ...
];

XList = {'AgeAttend_2_0'};

results.age_7n = LMM_with_EffectSizes_Full( ...
    UKB_BrainXY, ...
    formula, ...
    XList, ...
    YList);

% Quadratic age effect
UKB_BrainXY.AgeAttend_2_0_Sq = ...
    zscore(UKB_BrainXY.AgeAttend_2_0).^2;

formula = [ ...
    'AgeAttend_2_0+Sex_0_0+BMI_2_0+HeadMotion_2_0+', ...
    'Race_1+Race_2+Race_3+Race_4+Vol_WB_TIV_2_0+(1|Centre_0_0)' ...
];

XList = {'AgeAttend_2_0_Sq'};

results.age2_7n = LMM_with_EffectSizes_Full( ...
    UKB_BrainXY, ...
    formula, ...
    XList, ...
    YList);

% Sex
formula = [ ...
    'AgeAttend_2_0+BMI_2_0+HeadMotion_2_0+SNR_2_0+', ...
    'Race_1+Race_2+Race_3+Race_4+t1_vol_scaling_2_0+(1|Centre_0_0)' ...
];

XList = {'Sex_0_0'};

results.sex_7n = LMM_with_EffectSizes_Full( ...
    UKB_BrainXY, ...
    formula, ...
    XList, ...
    YList);

% BMI
formula = [ ...
    'Sex_0_0+AgeAttend_2_0+HeadMotion_2_0+SNR_2_0+', ...
    'Race_1+Race_2+Race_3+Race_4+t1_vol_scaling_2_0+(1|Centre_0_0)' ...
];

XList = {'BMI_2_0'};

results.bmi_7n = LMM_with_EffectSizes_Full( ...
    UKB_BrainXY, ...
    formula, ...
    XList, ...
    YList);

% T1 scaling
formula = [ ...
    'Sex_0_0+AgeAttend_2_0+BMI_2_0+HeadMotion_2_0+SNR_2_0+', ...
    'Race_1+Race_2+Race_3+Race_4+(1|Centre_0_0)' ...
];

XList = {'t1_vol_scaling_2_0'};

results.t1_scaling_7n = LMM_with_EffectSizes_Full( ...
    UKB_BrainXY, ...
    formula, ...
    XList, ...
    YList);

results.demo_7n = [ ...
    results.age_7n; ...
    results.age2_7n; ...
    results.sex_7n; ...
    results.bmi_7n; ...
    results.t1_scaling_7n ...
];

% Age x cognition interactions used in the original master script.
%
% x20016 and x137 are outcome/cognitive variables and are therefore joined
% explicitly from UKB_Outcomes_2_0 rather than assumed to exist in UKB_Basic.

X1List = {'x20016', 'x137'};
X2List = {'AgeAttend_2_0'};

interaction_formula = [ ...
    'Sex_0_0+AgeAttend_2_0^2+BMI_2_0+HeadMotion_2_0+SNR_2_0+', ...
    'Vol_WB_TIV_2_0+Race_1+Race_2+Race_3+Race_4+(1|Centre_0_0)' ...
];

if isempty(UKB_Outcomes_2_0)
    error(['UKB_Outcomes_2_0.csv is required for the age-by-cognition ', ...
           'interaction analyses.']);
end

required_cognitive = X1List;

if ~all(ismember(required_cognitive, ...
        UKB_Outcomes_2_0.Properties.VariableNames))
    error(['UKB_Outcomes_2_0.csv does not contain the exact variables ', ...
           'x20016 and x137 required by the original interaction analysis.']);
end

UKB_InteractXY = innerjoin(UKB_Basic, UKB_BrainMRICov, 'Keys', 'eid');
UKB_InteractXY = innerjoin( ...
    UKB_InteractXY, ...
    UKB_Outcomes_2_0(:, [{'eid'}, required_cognitive]), ...
    'Keys', ...
    'eid');
UKB_InteractXY = innerjoin(UKB_InteractXY, brain_data_7n, 'Keys', 'eid');

if ismember('HeadMotion_2_0', UKB_InteractXY.Properties.VariableNames)
    UKB_InteractXY(UKB_InteractXY.HeadMotion_2_0 > 0.2, :) = [];
end

results.interact_7n = LMM_withFormula_Interact( ...
    UKB_InteractXY, ...
    interaction_formula, ...
    X1List, ...
    X2List, ...
    YList);

% -------------------------------------------------------------------------
% Parcel-level age x cognition interaction
% -------------------------------------------------------------------------

UKB_BrainXY_360 = innerjoin(UKB_Basic, UKB_BrainMRICov, 'Keys', 'eid');
UKB_BrainXY_360 = innerjoin( ...
    UKB_BrainXY_360, ...
    UKB_Outcomes_2_0(:, [{'eid'}, required_cognitive]), ...
    'Keys', ...
    'eid');
UKB_BrainXY_360 = innerjoin(UKB_BrainXY_360, brain_data_360p, 'Keys', 'eid');

if ismember('HeadMotion_2_0', UKB_BrainXY_360.Properties.VariableNames)
    UKB_BrainXY_360(UKB_BrainXY_360.HeadMotion_2_0 > 0.2, :) = [];
end

YList360 = brain_data_360p.Properties.VariableNames(2:end)';

results.interact_360p = LMM_withFormula_Interact( ...
    UKB_BrainXY_360, ...
    interaction_formula, ...
    X1List, ...
    X2List, ...
    YList360);

% -------------------------------------------------------------------------
% Save
% -------------------------------------------------------------------------

result_dir = fullfile(OUTPUT_DIR, 'association_results');

if ~exist(result_dir, 'dir')
    mkdir(result_dir);
end

save( ...
    fullfile(result_dir, ...
    sprintf('demographic_age_results_%dTR.mat', window_length)), ...
    'results', ...
    '-v7.3');

end
